# Generated by Django 3.2.12 on 2023-04-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encoded', models.CharField(max_length=32, verbose_name='编码')),
                ('Type', models.CharField(max_length=16, verbose_name='所属分类')),
                ('EnterTime', models.DateTimeField(verbose_name='入场时间')),
                ('Name', models.CharField(max_length=16, verbose_name='姓名')),
                ('State', models.CharField(max_length=16, verbose_name='状态')),
            ],
            options={
                'verbose_name': '预约管理',
                'verbose_name_plural': '预约管理',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('Idnumber', models.BigIntegerField(verbose_name='身份证号码')),
            ],
        ),
    ]
