# Generated by Django 3.2.12 on 2023-04-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yn_museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='State',
            field=models.CharField(choices=[(2, '已入馆'), (1, '预约成功')], max_length=16, verbose_name='预约状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Type',
            field=models.CharField(choices=[(1, '参观预约'), (3, '展览预约'), (2, '活动预约')], max_length=16, verbose_name='所属分类'),
        ),
    ]
