# Generated by Django 3.2.12 on 2023-04-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yn_museum', '0002_auto_20230407_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': '访客管理 ', 'verbose_name_plural': '访客管理'},
        ),
        migrations.AlterField(
            model_name='order',
            name='State',
            field=models.CharField(choices=[('2', '已入馆'), ('1', '预约成功')], max_length=16, verbose_name='预约状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Type',
            field=models.CharField(choices=[('1', '参观预约'), ('3', '展览预约'), ('2', '活动预约')], max_length=16, verbose_name='所属分类'),
        ),
    ]
