# Generated by Django 3.2.12 on 2023-04-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yn_museum', '0003_auto_20230407_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='State',
            field=models.CharField(max_length=16, verbose_name='预约状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Type',
            field=models.CharField(max_length=16, verbose_name='所属分类'),
        ),
    ]
