# Generated by Django 3.2.12 on 2023-04-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yn_museum', '0004_auto_20230407_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='Idnumber',
            field=models.CharField(max_length=32, verbose_name='身份证号码'),
        ),
    ]
