# Generated by Django 3.2.12 on 2023-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yn_museum', '0005_alter_visitor_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Idnumber2',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='身份证号码'),
        ),
    ]
