# Generated by Django 3.2.12 on 2023-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yn_museum', '0007_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32, verbose_name='姓名')),
                ('Date', models.CharField(max_length=16, verbose_name='参观日期')),
                ('number', models.CharField(max_length=16, verbose_name='人数')),
                ('state', models.CharField(max_length=16, verbose_name='预约状态')),
                ('notes', models.CharField(max_length=32, verbose_name='备注')),
            ],
            options={
                'verbose_name': '团体预约管理',
                'verbose_name_plural': '团体预约管理',
            },
        ),
    ]
