"""
Django settings for museum project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_uz_3h-^$v0ri2j&e$4oot!j(b5+h382z3r*)9x3_)rh$ow#!3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
# 允许所有域名访问
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    "import_export",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "yn_museum",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'museum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'museum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    'default': {
        "ENGINE":'django.db.backends.mysql',
        'NAME':"django_workers",
        "USER":"root",
        "PASSWORD":"362413l.",
        "HOST":'db',
        "POST":3306,
        "OPTIONS":{"charset":"utf8"}
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# 设置中文，无时差
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# 自定义图标  图标网址：https://fontawesome.com/search
SIMPLEUI_ICON = {
    '团体预约管理': 'fa-solid fa-people-group',
    '上饶博物馆': 'fa-solid fa-building-columns',
    '预约管理': 'fa-solid fa-calendar-check',
    '访客管理': 'fa-solid fa-user',
    '预约类型': 'fa-solid fa-layer-group',


}
SIMPLEUI_INDEX = '/admin/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 关闭广告和快捷操作和最近操作
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False
# 自定义首页
SIMPLEUI_HOME_PAGE = '/total/'
SIMPLEUI_HOME_TITLE = '首页'
SIMPLEUI_HOME_ICON = 'fa fa-eye'

SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['上饶博物馆', '权限认证'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': False,
    'menus': [
        {
            'app': 'auth',
            'name': '权限认证',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fa fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': '用户组',
                    'icon': 'fa fa-th-list',
                    'url': 'auth/group/'
                }
            ]
        },

        {
            'name': '上饶博物馆',
            'icon': 'fa-solid fa-building-columns',
            'models': [
                {
                    'name': '预约管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/yn_museum/order/',
                    'icon': 'fa-solid fa-calendar-check'
                },
                {
                    'name': '团体预约管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/yn_museum/group/',
                    'icon': 'fa-solid fa-people-group'
                },
                {
                    'name': '访客管理',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/yn_museum/visitor/',
                    'icon': 'fa-solid fa-user'
                },
                {
                    'name': '预约类型',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/yn_museum/order_type/',
                    'icon': 'fa-solid fa-layer-group'
                },
            ]
        },
    ]
}
